language: node_js
env:
  - TEST_SUITE=jshint
  - TEST_SUITE=testem-test-vanillajs-jasmine
  - TEST_SUITE=testem-test-vanillajs-jasmine-blanket
  - TEST_SUITE=testem-test-vanillajs-mocha
  - TEST_SUITE=testem-test-vanillajs-mocha-blanket
  - TEST_SUITE=testem-test-vanillajs-qunit
  - TEST_SUITE=testem-test-vanillajs-qunit-blanket
  - TEST_SUITE=karma-test-vanillajs-jasmine
  - TEST_SUITE=karma-test-vanillajs-mocha
  - TEST_SUITE=karma-test-vanillajs-qunit
script: npm run $TEST_SUITE
sudo: false
